name = "Hugo Atlantic"
description = "A Hugo Tailwind blog theme"
homepage = "https://hugo-atlantic.netlify.com"
min_version = "0.74.3"

[author]
  name = "Robert Austin"
  homepage = "https://www.zerostatic.io"