baseURL = "/"
languageCode = "en-us"
title = "Hugo Atlantic"
theme = "hugo-atlantic-theme"
enableGitInfo = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
metaDataFormat = "yaml"
paginate = 6

[params]
  homepagePostLimit = 6
  
[build]
  writeStats = true

[permalinks]
    posts = "blog/:year/:month/:title/"
    pages = ":slug/"

[taxonomies]
    tag = "tags"
    category = "categories"
    author = "authors"
  
# Main Menu
[[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

# Footer Menu Primary
[[menu.footer_primary]]
	name = "Home"
	url = "/"
  weight = 1

[[menu.footer_primary]]
    name = "Blog"
    url = "/posts/"
    weight = 2

[[menu.footer_primary]]
    name = "Privacy Policy"
    url = "/privacy/"
    weight = 3